-- 验证会计科目配置
SELECT 
  JSON_EXTRACT(`value`, '$.ACCOUNTS_RECEIVABLE') as ACCOUNTS_RECEIVABLE,
  JSON_EXTRACT(`value`, '$.SALES_REVENUE') as SALES_REVENUE,
  JSON_EXTRACT(`value`, '$.ACCOUNTS_PAYABLE') as ACCOUNTS_PAYABLE,
  JSON_EXTRACT(`value`, '$.PURCHASE_COST') as PURCHASE_COST,
  JSON_EXTRACT(`value`, '$.COST_OF_GOODS_SOLD') as COST_OF_GOODS_SOLD,
  JSON_EXTRACT(`value`, '$.INVENTORY') as INVENTORY
FROM system_settings 
WHERE `key` = 'accounting.account_codes';

